// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsAggregation.Configurations.DatabaseConfigurations;

#nullable disable

namespace NewsAggregation.Migrations
{
    [DbContext(typeof(NewsAggregationDbContext))]
    [Migration("20250627055226_Seed-Data-Migration")]
    partial class SeedDataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewsAggregation.Entities.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExternalServerId")
                        .HasColumnType("int");

                    b.Property<int>("HideReason")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExternalServerId");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("NewsAggregation.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "All"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Technology"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Health"
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sports"
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Business"
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("NewsAggregation.Entities.ExternalServer", b =>
                {
                    b.Property<int>("ExternalServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExternalServerId"));

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ExternalServerId");

                    b.ToTable("ExternalServers");
                });

            modelBuilder.Entity("NewsAggregation.Entities.Keywords", b =>
                {
                    b.Property<int>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeywordId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("KeywordId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Keywords");

                    b.HasData(
                        new
                        {
                            KeywordId = 1,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "AI",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 2,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Blockchain",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 3,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Cloud",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 4,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Cybersecurity",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 5,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Data Science",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 6,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "DevOps",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 7,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Gadgets",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 8,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Innovation",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 9,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Programming",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 10,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Robotics",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 11,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Software",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 12,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Tech News",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 13,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Virtual Reality",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 14,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Web Development",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 15,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "5G",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 16,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Startups",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 17,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Mobile",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 18,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Hardware",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 19,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Networking",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 20,
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "AI Ethics",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 21,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Nutrition",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 22,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Mental Health",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 23,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Diseases",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 24,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Fitness",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 25,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Healthcare",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 26,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Medicine",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 27,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Wellness",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 28,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Yoga",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 29,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Pharmacy",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 30,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Public Health",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 31,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Surgery",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 32,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Vaccines",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 33,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Allergies",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 34,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Cardiology",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 35,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Dermatology",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 36,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Epidemiology",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 37,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Neurology",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 38,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Pediatrics",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 39,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Psychology",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 40,
                            CategoryId = 3,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Rehabilitation",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 41,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Football",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 42,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Basketball",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 43,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Tennis",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 44,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Cricket",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 45,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Olympics",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 46,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Athletics",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 47,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Baseball",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 48,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Golf",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 49,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Hockey",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 50,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Rugby",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 51,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Swimming",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 52,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Volleyball",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 53,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Wrestling",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 54,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Boxing",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 55,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Motorsport",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 56,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Cycling",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 57,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Gymnastics",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 58,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Skiing",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 59,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Surfing",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 60,
                            CategoryId = 4,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Skateboarding",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 61,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Economy",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 62,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Finance",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 63,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Markets",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 64,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Investing",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 65,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Startups",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 66,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Real Estate",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 67,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Banking",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 68,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Business News",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 69,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Entrepreneurship",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 70,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Trade",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 71,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Taxes",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 72,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Insurance",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 73,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Retail",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 74,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Management",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 75,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Marketing",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 76,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Sales",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 77,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Strategy",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 78,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Supply Chain",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 79,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Technology",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 80,
                            CategoryId = 5,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Leadership",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 81,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Movies",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 82,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Music",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 83,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "TV Shows",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 84,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Celebrities",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 85,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Awards",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 86,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Theater",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 87,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Streaming",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 88,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Pop Culture",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 89,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Concerts",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 90,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Festivals",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 91,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Documentaries",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 92,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Animation",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 93,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Comedy",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 94,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Drama",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 95,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Fashion",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 96,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Gaming",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 97,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Hollywood",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 98,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Bollywood",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 99,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Reviews",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            KeywordId = 100,
                            CategoryId = 6,
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Interviews",
                            ModifiedBy = "System",
                            ModifiedDateTime = new DateTime(2025, 6, 27, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("NewsAggregation.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserArticleReaction", b =>
                {
                    b.Property<int>("UserArticleReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserArticleReactionId"));

                    b.Property<DateTime>("ActionCreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("Reaction")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserArticleReactionId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserArticleReactions");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserArticleReport", b =>
                {
                    b.Property<int>("UserArticleReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserArticleReportId"));

                    b.Property<DateTime>("ActionCreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("ReportReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserArticleReportId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserArticleReports");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserKeyword", b =>
                {
                    b.Property<int>("UserKeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserKeywordId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserKeywordId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserKeywords");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserNotification", b =>
                {
                    b.Property<int>("UserNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserNotificationId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserNotificationId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserNotificationConfiguration", b =>
                {
                    b.Property<int>("UserNotificationConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserNotificationConfigurationId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserNotificationConfigurationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotificationConfigurations");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserSavedArticle", b =>
                {
                    b.Property<int>("UserSavedArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSavedArticleId"));

                    b.Property<DateTime>("ActionCreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserSavedArticleId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSavedArticles");
                });

            modelBuilder.Entity("NewsAggregation.Entities.Article", b =>
                {
                    b.HasOne("NewsAggregation.Entities.Category", null)
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NewsAggregation.Entities.ExternalServer", null)
                        .WithMany()
                        .HasForeignKey("ExternalServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NewsAggregation.Entities.Keywords", b =>
                {
                    b.HasOne("NewsAggregation.Entities.Category", "Category")
                        .WithMany("Keywords")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserArticleReaction", b =>
                {
                    b.HasOne("NewsAggregation.Entities.Article", "Article")
                        .WithMany("UserArticleReactions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAggregation.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserArticleReport", b =>
                {
                    b.HasOne("NewsAggregation.Entities.Article", "Article")
                        .WithMany("UserArticleReports")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAggregation.Entities.User", "User")
                        .WithMany("UserArticleReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserKeyword", b =>
                {
                    b.HasOne("NewsAggregation.Entities.Category", "Category")
                        .WithMany("UserKeywords")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAggregation.Entities.User", "User")
                        .WithMany("UserKeywords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserNotification", b =>
                {
                    b.HasOne("NewsAggregation.Entities.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAggregation.Entities.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserNotificationConfiguration", b =>
                {
                    b.HasOne("NewsAggregation.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAggregation.Entities.User", "User")
                        .WithMany("UserNotificationConfigurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsAggregation.Entities.UserSavedArticle", b =>
                {
                    b.HasOne("NewsAggregation.Entities.Article", "Article")
                        .WithMany("UserSavedArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAggregation.Entities.User", "User")
                        .WithMany("UserSavedArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsAggregation.Entities.Article", b =>
                {
                    b.Navigation("UserArticleReactions");

                    b.Navigation("UserArticleReports");

                    b.Navigation("UserSavedArticles");
                });

            modelBuilder.Entity("NewsAggregation.Entities.Category", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Keywords");

                    b.Navigation("UserKeywords");
                });

            modelBuilder.Entity("NewsAggregation.Entities.User", b =>
                {
                    b.Navigation("UserArticleReports");

                    b.Navigation("UserKeywords");

                    b.Navigation("UserNotificationConfigurations");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserSavedArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
